services:
  node:
    restart: always
    build: .
    volumes:
      - ./:/usr/src/app

  mongo:
    image: mongo:8.0.0-rc7
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: example